# Generated by Django 3.1.2 on 2020-11-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_contexts', '0004_editorialboardlocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialboardlocks',
            options={'ordering': ('-locked_time',), 'verbose_name_plural': 'Editorial Board Locks'},
        ),
    ]
