# Generated by Django 3.1.2 on 2020-12-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cms', '0001_initial'),
        ('cms_carousels', '0002_auto_20201202_1650'),
        ('cms_contexts', '0001_initial'),
        ('cms_medias', '0001_initial'),
        ('cms_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationgallery',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_medias.mediacollection'),
        ),
        migrations.AddField(
            model_name='publicationgallery',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.publication'),
        ),
        migrations.AddField(
            model_name='publicationcontext',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contpub_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationcontext',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contpub_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationcontext',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.publication'),
        ),
        migrations.AddField(
            model_name='publicationcontext',
            name='webpath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_contexts.webpath'),
        ),
        migrations.AddField(
            model_name='publicationblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_templates.templateblock'),
        ),
        migrations.AddField(
            model_name='publicationblock',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.publication'),
        ),
        migrations.AddField(
            model_name='publicationattachment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_attachment', to='cms.publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ManyToManyField(to='cms.Category'),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='presentation_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_medias.media'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='pagerelated',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_page', to='cms.page'),
        ),
        migrations.AddField(
            model_name='pagerelated',
            name='related_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_page', to='cms.page'),
        ),
        migrations.AddField(
            model_name='pagemenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_menus.navigationbar'),
        ),
        migrations.AddField(
            model_name='pagemenu',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AddField(
            model_name='pagecarousel',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_carousels.carousel'),
        ),
        migrations.AddField(
            model_name='pagecarousel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_templates.templateblock'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='base_template',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_templates.pagetemplate'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='page',
            name='webpath',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_contexts.webpath'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationrelated',
            unique_together={('publication', 'related')},
        ),
        migrations.AlterUniqueTogether(
            name='pagerelated',
            unique_together={('page', 'related_page')},
        ),
    ]
