# Generated by Django 3.1.2 on 2020-10-29 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_context', '0001_initial'),
        ('cms', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cms_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='context',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='cms_context.WebPath'),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='pagethirdpartyblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.pageblock'),
        ),
        migrations.AddField(
            model_name='pagethirdpartyblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AddField(
            model_name='pagerelated',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_page', to='cms.page'),
        ),
        migrations.AddField(
            model_name='pagerelated',
            name='related_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_page', to='cms.page'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='base_template',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_templates.pagetemplate'),
        ),
        migrations.AddField(
            model_name='page',
            name='context',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_context.webpath'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='navigationbaritem',
            name='context',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_context.webpath'),
        ),
        migrations.AddField(
            model_name='navigationbaritem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_path', to='cms_context.webpath'),
        ),
        migrations.AddField(
            model_name='navigationbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_page', to='cms.navigationbaritem'),
        ),
        migrations.AddField(
            model_name='navigationbaritem',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pub', to='cms.publication'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationrelated',
            unique_together={('publication', 'related')},
        ),
        migrations.AlterUniqueTogether(
            name='pagerelated',
            unique_together={('page', 'related_page')},
        ),
    ]
