# Generated by Django 3.1.2 on 2020-10-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201010_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name_plural': 'Publications'},
        ),
    ]
