# Generated by Django 3.1.2 on 2020-11-16 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201114_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 0)),
            preserve_default=False,
        ),
    ]
