# Generated by Django 3.1.2 on 2020-10-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201011_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Content Categories'},
        ),
    ]
