# Generated by Django 3.1.2 on 2020-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201007_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ManyToManyField(to='cms.SubCategory'),
        ),
    ]
