# Generated by Django 3.1.2 on 2020-10-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_page_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Content Categories'},
        ),
        migrations.AlterModelOptions(
            name='pageblocklocalization',
            options={'verbose_name_plural': 'Page Third-Party Blocks'},
        ),
        migrations.RenameField(
            model_name='pageblocklocalization',
            old_name='page_block',
            new_name='block',
        ),
        migrations.CreateModel(
            name='PageThirdPartyBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.pageblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'verbose_name_plural': 'Page Block',
            },
        ),
    ]
