# Generated by Django 3.1.2 on 2020-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201012_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritem',
            name='url',
            field=models.CharField(blank=True, help_text='url', max_length=2048, null=True),
        ),
    ]
