# Generated by Django 3.1.2 on 2020-12-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201209_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationattachment',
            old_name='file_format',
            new_name='file_type',
        ),
    ]
