# Generated by Django 3.1.2 on 2020-11-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201116_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblock',
            name='section',
        ),
    ]
