# Generated by Django 3.1.2 on 2020-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_context', '0001_initial'),
        ('cms', '0003_contextpublicationattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextpublication',
            name='context',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='cms_context.EditorialBoardContext'),
        ),
    ]
