# Generated by Django 3.1.2 on 2020-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201010_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=1024)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='images/categories')),
            ],
            options={
                'verbose_name_plural': 'Page Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ManyToManyField(to='cms.Category'),
        ),
    ]
