# Generated by Django 3.1.2 on 2020-10-11 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201011_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(help_text='url')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.publication')),
            ],
            options={
                'verbose_name_plural': 'Publication Links',
            },
        ),
    ]
