# Generated by Django 3.1.2 on 2020-10-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201012_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationlocalization',
            name='title',
            field=models.CharField(default='', help_text='Heading, Headline', max_length=256),
            preserve_default=False,
        ),
    ]
