# Generated by Django 3.1.2 on 2020-11-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_pageblock_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblock',
            name='order',
        ),
    ]
