# Generated by Django 3.1.2 on 2020-10-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201010_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextpublicationattachment',
            options={'verbose_name_plural': 'Publication Attachments'},
        ),
    ]
