# Generated by Django 3.1.2 on 2020-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201007_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagethirdpartyblock',
            options={'verbose_name_plural': 'Page Third-Party Block'},
        ),
        migrations.AddField(
            model_name='pagethirdpartyblock',
            name='section',
            field=models.CharField(blank=True, help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True),
        ),
    ]
