# Generated by Django 3.1.2 on 2020-10-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_navigationbaritemlocalization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritemlocalization',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en', max_length=12),
        ),
        migrations.AlterField(
            model_name='publicationlocalization',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en', max_length=12),
        ),
    ]
