# Generated by Django 3.1.2 on 2020-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20201007_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='images/categories'),
        ),
    ]
