# Generated by Django 3.1.2 on 2020-10-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20201029_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationbaritemlocalization',
            name='item',
        ),
        migrations.DeleteModel(
            name='NavigationBarItem',
        ),
        migrations.DeleteModel(
            name='NavigationBarItemLocalization',
        ),
    ]
