# Generated by Django 3.1.2 on 2020-10-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20201007_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextNavBarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=33)),
                ('url', models.URLField(help_text='url')),
                ('context', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms.contextbasepagetemplate')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_page', to='cms.contextnavbaritem')),
            ],
            options={
                'verbose_name_plural': 'Context Navigation Menu Items',
            },
        ),
    ]
