# Generated by Django 3.1.2 on 2020-11-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0009_auto_20201118_1458'),
        ('cms', '0006_auto_20201118_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblock',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='type',
        ),
        migrations.AddField(
            model_name='pageblock',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms_templates.templateblock'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PageThirdPartyBlock',
        ),
    ]
