# Generated by Django 3.1.2 on 2020-10-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_contextnavbaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextnavbaritem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
    ]
