# Generated by Django 3.1.2 on 2020-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20201122_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='content_types',
            field=models.CharField(blank=True, choices=[('markdown', 'markdown'), ('html', 'html')], max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=33),
        ),
        migrations.AlterField(
            model_name='publication',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=33),
        ),
    ]
