# Generated by Django 3.1.2 on 2020-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cms_context', '0001_initial'),
        ('cms', '0008_contextnavbaritem_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContextBasePageTemplate',
            new_name='ContextBasePage',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='template',
        ),
        migrations.AddField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[], default='base.html', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('/home/wert/DEV3/Portale-PoC/unicms/cms_templates/pages/base.html', 'base.html')], max_length=1024),
        ),
    ]
