# Generated by Django 3.1.2 on 2020-10-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20201008_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextbasepage',
            options={'ordering': ['name'], 'verbose_name_plural': 'Context Base Pages'},
        ),
        migrations.AlterField(
            model_name='contextnavbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_page', to='cms.contextnavbaritem'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='section',
            field=models.CharField(blank=True, choices=[('head', 'Header'), ('menu', 'Navigation Menu'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('footer', 'Footer')], help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='section',
            field=models.CharField(blank=True, choices=[('head', 'Header'), ('menu', 'Navigation Menu'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('footer', 'Footer')], help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pagethirdpartyblock',
            name='section',
            field=models.CharField(blank=True, choices=[('head', 'Header'), ('menu', 'Navigation Menu'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('footer', 'Footer')], help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True),
        ),
    ]
