# Generated by Django 3.1.2 on 2020-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20201008_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextnavbaritem',
            name='url',
            field=models.URLField(blank=True, help_text='url', null=True),
        ),
    ]
