# Generated by Django 3.1.2 on 2020-11-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20201122_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='content_types',
        ),
        migrations.AddField(
            model_name='publication',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'markdown'), ('html', 'html')], default='markdown', max_length=33),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(blank=True, help_text='Content', null=True),
        ),
    ]
