# Generated by Django 3.1.2 on 2020-10-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_contextbasepagethirdpartyblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplateThirdPartyBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('section', models.CharField(blank=True, choices=[('head', 'Header'), ('menu', 'Navigation Menu'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('footer', 'Footer')], help_text='Specify the container section in the template where this block would be rendered.', max_length=33, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.pageblock')),
                ('template', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms.pagetemplate')),
            ],
            options={
                'verbose_name_plural': 'Page Template Third-Party Block',
            },
        ),
        migrations.DeleteModel(
            name='ContextBasePageThirdPartyBlock',
        ),
    ]
