# Generated by Django 3.1.2 on 2020-11-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_medias', '0003_delete_medialink'),
        ('cms', '0014_auto_20201109_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='presentation_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_medias.media'),
        ),
    ]
