# Generated by Django 3.1.2 on 2020-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20201201_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, help_text='SEO HTTP meta description', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='keys',
            field=models.CharField(blank=True, help_text='SEO HTTP meta keys', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.CharField(blank=True, help_text='SEO HTTP meta description', max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='keys',
            field=models.CharField(blank=True, help_text='SEO HTTP meta keys', max_length=256, null=True),
        ),
    ]
