# Generated by Django 3.1.2 on 2020-11-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_publication_presentation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcontext',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
