# Generated by Django 3.1.2 on 2020-11-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_publicationcontext_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationlocalization',
            old_name='context_publication',
            new_name='publication',
        ),
    ]
