# Generated by Django 3.1.3 on 2020-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20201109_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='type',
            field=models.TextField(choices=[('cms_templates.blocks.NullBlock', 'Null Block'), ('cms_templates.blocks.HtmlBlock', 'HTML Block'), ('cms_templates.blocks.JSONBlock', 'JSON Block'), ('unical.flescaTeam.custom_blocks.AngularJSONBlock', 'Angular JSON Block')]),
        ),
    ]
