# Generated by Django 3.1.2 on 2020-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20201201_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='note',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, help_text='Descriptionused for SEO.', null=True),
        ),
    ]
