# Generated by Django 3.1.2 on 2020-10-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_medias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='name',
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, help_text='Media file title', max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Link title', max_length=60, null=True)),
                ('url', models.TextField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_medias.media')),
            ],
            options={
                'verbose_name_plural': 'Media Links',
            },
        ),
    ]
