# Generated by Django 3.1.2 on 2020-10-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_medias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='context',
        ),
    ]
