# Generated by Django 3.1.2 on 2020-10-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_medias', '0002_auto_20201012_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='collections',
        ),
        migrations.CreateModel(
            name='MediaCollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_medias.mediacollection')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_medias.media')),
            ],
            options={
                'verbose_name_plural': 'Media Collection Items',
                'ordering': ['order'],
            },
        ),
    ]
