# Generated by Django 3.1.2 on 2020-12-09 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_medias', '0002_auto_20201209_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacollection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediacollection_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediacollection_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediacollectionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediacollectionitem_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediacollectionitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediacollectionitem_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
