# Generated by Django 3.1.2 on 2020-10-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_medias', '0002_remove_media_context'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaLink',
        ),
    ]
