# Generated by Django 3.1.2 on 2020-10-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_medias', '0003_auto_20201012_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediacollectionitem',
            name='collection',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_medias.mediacollection'),
        ),
        migrations.AlterField(
            model_name='mediacollectionitem',
            name='media',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_medias.media'),
        ),
    ]
