# Generated by Django 3.1.2 on 2020-10-30 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_context', '0001_initial'),
        ('cms_menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationbaritem',
            name='context',
        ),
        migrations.RemoveField(
            model_name='navigationbaritem',
            name='page',
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=33)),
                ('context', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_context.webpath')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Context Navigation Menus',
            },
        ),
        migrations.AddField(
            model_name='navigationbaritem',
            name='manu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_page', to='cms_menus.navigationbar'),
        ),
    ]
