# Generated by Django 3.1.2 on 2020-11-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritem',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
