# Generated by Django 3.1.2 on 2020-11-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_contexts', '0001_initial'),
        ('cms_menus', '0002_auto_20201119_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationbaritem',
            name='page',
        ),
        migrations.AddField(
            model_name='navigationbaritem',
            name='webpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_page', to='cms_contexts.webpath'),
        ),
    ]
