# Generated by Django 3.1.2 on 2020-10-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_menus', '0003_auto_20201030_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationbaritem',
            old_name='manu',
            new_name='menu',
        ),
    ]
