# Generated by Django 3.1.2 on 2020-12-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20201124_1412'),
        ('cms_menus', '0003_auto_20201119_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbaritem',
            name='inherited_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherited_content', to='cms.publication'),
        ),
    ]
