# Generated by Django 3.1.2 on 2020-12-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20201124_1412'),
        ('cms_menus', '0004_navigationbaritem_inherited_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbaritem',
            name='inherited_content',
            field=models.ForeignKey(blank=True, help_text='Takes additional contents from a publication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inherited_content', to='cms.publication'),
        ),
    ]
