# Generated by Django 3.1.2 on 2020-10-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20201030_1334'),
        ('cms_menus', '0004_auto_20201030_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbaritem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_page', to='cms.page'),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_menu', to='cms_menus.navigationbar'),
        ),
        migrations.AlterField(
            model_name='navigationbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_parent', to='cms_menus.navigationbaritem'),
        ),
    ]
