# Generated by Django 3.1.2 on 2020-11-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_menus', '0006_remove_navigationbar_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationbar',
            name='section',
        ),
    ]
