# Generated by Django 3.1.3 on 2020-11-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_menus', '0007_remove_navigationbar_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationbaritem',
            options={'ordering': ('order',), 'verbose_name_plural': 'Context Navigation Menu Items'},
        ),
    ]
