# Generated by Django 3.1.2 on 2020-10-29 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=2048)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Carousels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('pre_heading', models.CharField(blank=True, help_text='Pre Heading', max_length=120, null=True)),
                ('heading', models.CharField(blank=True, help_text='Heading', max_length=120, null=True)),
                ('description', models.TextField()),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_carousels.carousel')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_medias.media')),
            ],
            options={
                'verbose_name_plural': 'Carousel Items',
            },
        ),
        migrations.CreateModel(
            name='CarouselItemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(blank=True, help_text='Title', max_length=120, null=True)),
                ('url', models.CharField(max_length=2048)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_carousels.carouselitem')),
            ],
            options={
                'verbose_name_plural': 'Carousel Item Links',
            },
        ),
    ]
