# Generated by Django 3.1.2 on 2020-12-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_medias', '0001_initial'),
        ('cms_carousels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_medias.media'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carousel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
