# Generated by Django 3.1.2 on 2020-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_carousels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='carouselitemlink',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
