# Generated by Django 3.1.2 on 2020-12-09 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_carousels', '0002_auto_20201202_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitem_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitem_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carouselitemlinklocalization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitemlinklocalization_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carouselitemlinklocalization',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitemlinklocalization_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carouselitemlocalization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitemlocalization_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carouselitemlocalization',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carouselitemlocalization_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
