# Generated by Django 3.1.2 on 2020-10-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_carousels', '0005_carousel_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='section',
        ),
    ]
