# Generated by Django 3.1.2 on 2020-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_carousels', '0009_carouselitemlinklocalization_title_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitemlinklocalization',
            name='title_preset',
        ),
        migrations.AddField(
            model_name='carouselitemlink',
            name='title_preset',
            field=models.CharField(choices=[('view', 'View'), ('open', 'Open'), ('read more', 'Read More'), ('more', 'More'), ('get in', 'Get in'), ('enter', 'Enter'), ('submit', 'Submit'), ('custom', 'custom')], default='custom', max_length=33),
        ),
    ]
