# Generated by Django 3.1.2 on 2020-10-05 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoardContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254)),
                ('path', models.TextField(max_length=2048)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'EditorialBoard Site Contexts',
            },
        ),
        migrations.CreateModel(
            name='EditorialBoardRolePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('permission', models.CharField(choices=[('-1', 'nothing'), ('0', 'everything'), ('1', 'can edit created by him/her'), ('2', 'can edit all pages in his/her context'), ('3', 'can edit all pages'), ('4', 'can edit his/her own'), ('5', 'can translate all pages in his/her context'), ('6', 'can translate all pages'), ('7', 'can publish created by him/her'), ('8', 'can publish all pages in his/her context'), ('9', 'can publish all pages')], max_length=5)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'EditorialBoard Role Permissions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fqdn', models.CharField(help_text='server FQDN', max_length=160, unique=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'EditorialBoard Sites',
            },
        ),
        migrations.CreateModel(
            name='EditorialBoardUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_context.editorialboardcontext')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_context.editorialboardrolepermissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EditorialBoard Context Users',
            },
        ),
        migrations.AddField(
            model_name='editorialboardcontext',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_context.site'),
        ),
    ]
