# Generated by Django 3.1.2 on 2020-11-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpath',
            name='fullpath',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='webpath',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='path be prefixed with the parent one, on save', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_path', to='cms_context.webpath'),
        ),
    ]
