# Generated by Django 3.1.2 on 2020-10-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201010_2222'),
        ('cms_pages', '0002_auto_20201010_1817'),
        ('cms_context', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditorialBoardContext',
            new_name='WebPath',
        ),
    ]
