# Generated by Django 3.1.2 on 2020-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_context', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='permission',
            field=models.CharField(choices=[('1', 'can edit created by him/her'), ('2', 'can edit all pages in his/her context'), ('3', 'can edit all pages in his/her context and descendants'), ('4', 'can translate all pages in his/her context'), ('5', 'can translate all pages in his/her context and descendants'), ('6', 'can publish created by him/her'), ('7', 'can publish all pages in his/her context'), ('8', 'can publish all pages in his/her context and descendants'), ('9', 'can publish all pages')], max_length=5),
        ),
    ]
