# Generated by Django 3.1.2 on 2020-10-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_context', '0002_auto_20201006_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialboardcontext',
            options={'verbose_name_plural': '2. Site Contexts'},
        ),
        migrations.AlterModelOptions(
            name='editorialboardeditors',
            options={'verbose_name_plural': '3. Context Editors'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': '1. Sites'},
        ),
    ]
