# Generated by Django 3.1.2 on 2020-10-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_context', '0002_auto_20201010_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialboardeditors',
            options={'verbose_name_plural': 'Editorial Board Users'},
        ),
        migrations.AlterModelOptions(
            name='webpath',
            options={'verbose_name_plural': 'Site Contexts (WebPaths)'},
        ),
    ]
