# Generated by Django 3.1.3 on 2020-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_context', '0003_auto_20201107_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardeditors',
            name='permission',
            field=models.CharField(choices=[('1', 'can edit created by him/her in his/her context'), ('2', 'can edit all pages in his/her context'), ('3', 'can edit all pages in his/her context and descendants'), ('4', 'can translate all pages in his/her context'), ('5', 'can translate all pages in his/her context and descendants'), ('6', 'can publish created by him/her in his/her context'), ('7', 'can publish all pages in his/her context'), ('8', 'can publish all pages in his/her context and descendants')], max_length=5),
        ),
    ]
