# Generated by Django 3.1.2 on 2020-11-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_context', '0004_auto_20201111_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorialboardeditors',
            old_name='context',
            new_name='webpath',
        ),
    ]
