# Generated by Django 3.1.2 on 2020-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmspages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='relevance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
