# Generated by Django 3.1.3 on 2020-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[('breadcrumbs.html', 'breadcrumbs.html'), ('publications_preview_v3.html', 'publications_preview_v3.html'), ('unical_portale_home_news_presta.html', 'unical_portale_home_news_presta.html'), ('unical_portale_menu_secondario.html', 'unical_portale_menu_secondario.html'), ('unical_portale_home_avvisi.html', 'unical_portale_home_avvisi.html'), ('unical_portale_home_news.html', 'unical_portale_home_news.html'), ('unical_portale_agenda.html', 'unical_portale_agenda.html'), ('publications_preview.html', 'publications_preview.html'), ('unical_portale_home_avvisi_presta.html', 'unical_portale_home_avvisi_presta.html'), ('unical_portale_agenda_presta.html', 'unical_portale_agenda_presta.html'), ('unical_portale_home_avvisi_v3.html', 'unical_portale_home_avvisi_v3.html')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('portale_home_v1.html', 'portale_home_v1.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_v_original.html', 'portale_home_v_original.html'), ('portale_home_v3.html', 'portale_home_v3.html'), ('portale_home_v2.html', 'portale_home_v2.html'), ('publication_list.html', 'publication_list.html')], max_length=1024),
        ),
    ]
