# Generated by Django 3.1.2 on 2020-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblocktemplate',
            name='schema',
        ),
        migrations.AddField(
            model_name='pageblocktemplate',
            name='type',
            field=models.TextField(choices=[('unicms.cms_templates.HTMLBlock', 'HTML Block'), ('unicms.cms_templates.JSONBlock', 'JSON Block')], default='unicms.cms_templates.HTMLBlock'),
            preserve_default=False,
        ),
    ]
