# Generated by Django 3.1.2 on 2020-10-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[], max_length=1024),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('/home/wert/DEV/Portale-PoC/unicms/templates/pages/base.html', 'base.html')], max_length=1024),
        ),
    ]
