# Generated by Django 3.1.2 on 2020-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0002_auto_20201010_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('base.html', 'base.html')], max_length=1024),
        ),
    ]
