# Generated by Django 3.1.2 on 2020-10-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0003_auto_20201018_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageblocktemplate',
            old_name='template',
            new_name='page_template',
        ),
    ]
