# Generated by Django 3.1.2 on 2020-10-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0004_auto_20201018_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageblocktemplate',
            options={'ordering': ['name'], 'verbose_name_plural': 'Block Templates'},
        ),
        migrations.RemoveField(
            model_name='pageblocktemplate',
            name='page_template',
        ),
        migrations.AddField(
            model_name='pagetemplate',
            name='blocks',
            field=models.ManyToManyField(to='cms_templates.PageBlockTemplate'),
        ),
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[('', 'No templates found')], max_length=1024),
        ),
    ]
