# Generated by Django 3.1.2 on 2020-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0004_remove_pageblocktemplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblocktemplate',
            name='content',
            field=models.TextField(blank=True, help_text='according to the block template schema', null=True),
        ),
    ]
