# Generated by Django 3.1.2 on 2020-11-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0004_auto_20201118_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblocktemplate',
            name='template_file',
        ),
        migrations.RemoveField(
            model_name='pagetemplate',
            name='blocks',
        ),
        migrations.AddField(
            model_name='pageblocktemplate',
            name='template',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_templates.pagetemplate'),
            preserve_default=False,
        ),
    ]
