# Generated by Django 3.1.2 on 2020-11-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0005_auto_20201118_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplateBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('section', models.CharField(blank=True, choices=[('pre-head', 'Pre-Header'), ('head', 'Header'), ('menu-1', 'Navigation Main Menu'), ('menu-2', 'Navigation Menu 2'), ('menu-3', 'Navigation Menu 3'), ('menu-4', 'Navigation Menu 4'), ('slider', 'Carousel/Slider'), ('slider-2', 'Carousel/Slider 2'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('pre-footer', 'Pre-Footer'), ('footer', 'Footer'), ('post-footer', 'Post-Footer')], help_text='Specify the container section in the template where this block would be rendered.', max_length=33, null=True)),
            ],
            options={
                'verbose_name_plural': 'Page Template Third-Party Blocks',
            },
        ),
        migrations.CreateModel(
            name='TemplateBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(blank=True, help_text='Specify the container section in the template where this block would be rendered.', max_length=60, null=True)),
                ('type', models.TextField(choices=[('cms_templates.blocks.NullBlock', 'Null Block'), ('cms_templates.blocks.HtmlBlock', 'HTML Block'), ('cms_templates.blocks.JSONBlock', 'JSON Block'), ('unical.flescaTeam.custom_blocks.AngularJSONBlock', 'Angular JSON Block')])),
                ('content', models.TextField(blank=True, help_text='according to the block template schema', null=True)),
            ],
            options={
                'verbose_name_plural': 'Page Template Blocks',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='pagetemplatethirdpartyblock',
            name='block',
        ),
        migrations.RemoveField(
            model_name='pagetemplatethirdpartyblock',
            name='template',
        ),
        migrations.DeleteModel(
            name='PageBlockTemplate',
        ),
        migrations.DeleteModel(
            name='PageTemplateThirdPartyBlock',
        ),
        migrations.AddField(
            model_name='pagetemplateblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_templates.templateblock'),
        ),
        migrations.AddField(
            model_name='pagetemplateblock',
            name='template',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='cms_templates.pagetemplate'),
        ),
    ]
