# Generated by Django 3.1.2 on 2020-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0005_pageblocktemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[('unical_portale_home_news.html', 'unical_portale_home_news.html'), ('unical_portale_home_avvisi_presta.html', 'unical_portale_home_avvisi_presta.html'), ('unical_portale_agenda.html', 'unical_portale_agenda.html'), ('unical_portale_home_news_presta.html', 'unical_portale_home_news_presta.html'), ('unical_portale_menu_secondario.html', 'unical_portale_menu_secondario.html'), ('unical_portale_agenda_presta.html', 'unical_portale_agenda_presta.html'), ('unical_portale_home_avvisi.html', 'unical_portale_home_avvisi.html')], max_length=1024),
        ),
    ]
