# Generated by Django 3.1.2 on 2020-11-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0007_auto_20201109_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[('publications_preview.html', 'publications_preview.html'), ('unical_portale_home_avvisi.html', 'unical_portale_home_avvisi.html'), ('unical_portale_menu_secondario.html', 'unical_portale_menu_secondario.html'), ('unical_portale_home_avvisi_presta.html', 'unical_portale_home_avvisi_presta.html'), ('unical_portale_home_news_presta.html', 'unical_portale_home_news_presta.html'), ('unical_portale_agenda_presta.html', 'unical_portale_agenda_presta.html'), ('unical_portale_agenda.html', 'unical_portale_agenda.html'), ('unical_portale_home_news.html', 'unical_portale_home_news.html')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('unical_portale_base.html', 'unical_portale_base.html'), ('unical_portale_base_presta.html', 'unical_portale_base_presta.html'), ('base.html', 'base.html')], max_length=1024),
        ),
    ]
