# Generated by Django 3.1.2 on 2020-11-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0007_remove_templateblock_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetemplateblock',
            options={'verbose_name_plural': 'Page Template Blocks'},
        ),
    ]
