# Generated by Django 3.1.2 on 2020-11-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0008_auto_20201118_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateblock',
            options={'ordering': ['name'], 'verbose_name_plural': 'Template Blocks'},
        ),
        migrations.AddField(
            model_name='templateblock',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this block', null=True),
        ),
    ]
