# Generated by Django 3.1.3 on 2020-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0008_auto_20201110_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[('unical_portale_home_news_presta.html', 'unical_portale_home_news_presta.html'), ('unical_portale_menu_secondario.html', 'unical_portale_menu_secondario.html'), ('unical_portale_home_avvisi.html', 'unical_portale_home_avvisi.html'), ('unical_portale_home_news.html', 'unical_portale_home_news.html'), ('unical_portale_agenda.html', 'unical_portale_agenda.html'), ('publications_preview.html', 'publications_preview.html'), ('unical_portale_home_avvisi_presta.html', 'unical_portale_home_avvisi_presta.html'), ('unical_portale_agenda_presta.html', 'unical_portale_agenda_presta.html')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='type',
            field=models.TextField(choices=[('cms_templates.blocks.NullBlock', 'Null Block'), ('cms_templates.blocks.HtmlBlock', 'HTML Block'), ('cms_templates.blocks.JSONBlock', 'JSON Block'), ('unical.flescaTeam.custom_blocks.AngularJSONBlock', 'Angular JSON Block')]),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('base.html', 'base.html'), ('publication_view.html', 'publication_view.html'), ('unical_portale_base_presta.html', 'unical_portale_base_presta.html'), ('unical_portale_base.html', 'unical_portale_base.html')], max_length=1024),
        ),
    ]
