# Generated by Django 3.1.3 on 2020-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0009_auto_20201111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='blocks',
            field=models.ManyToManyField(blank=True, null=True, to='cms_templates.PageBlockTemplate'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('portale_home_v1.html', 'portale_home_v1.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_v3.html', 'portale_home_v3.html'), ('portale_home_v2.html', 'portale_home_v2.html'), ('unical_portale_base_presta.html', 'unical_portale_base_presta.html'), ('unical_portale_base.html', 'unical_portale_base.html')], max_length=1024),
        ),
    ]
