# Generated by Django 3.1.3 on 2020-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0010_auto_20201111_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblocktemplate',
            name='template_file',
            field=models.CharField(choices=[('publications_preview_v3.html', 'publications_preview_v3.html'), ('unical_portale_home_news_presta.html', 'unical_portale_home_news_presta.html'), ('unical_portale_menu_secondario.html', 'unical_portale_menu_secondario.html'), ('unical_portale_home_avvisi.html', 'unical_portale_home_avvisi.html'), ('unical_portale_home_news.html', 'unical_portale_home_news.html'), ('unical_portale_agenda.html', 'unical_portale_agenda.html'), ('publications_preview.html', 'publications_preview.html'), ('unical_portale_home_avvisi_presta.html', 'unical_portale_home_avvisi_presta.html'), ('unical_portale_agenda_presta.html', 'unical_portale_agenda_presta.html'), ('unical_portale_home_avvisi_v3.html', 'unical_portale_home_avvisi_v3.html')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='cms_templates.PageBlockTemplate'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('portale_home_v1.html', 'portale_home_v1.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_v3.html', 'portale_home_v3.html'), ('portale_home_v2.html', 'portale_home_v2.html')], max_length=1024),
        ),
    ]
