# Generated by Django 3.1.3 on 2020-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0010_auto_20201119_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('portale_home_v1.html', 'portale_home_v1.html'), ('publication_view_hero_original.html', 'publication_view_hero_original.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_v_original.html', 'portale_home_v_original.html'), ('portale_home_v3.html', 'portale_home_v3.html'), ('publication_list_brython.html', 'publication_list_brython.html'), ('portale_home_v2.html', 'portale_home_v2.html'), ('publication_list.html', 'publication_list.html')], max_length=1024),
        ),
    ]
