# Generated by Django 3.1.2 on 2020-11-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0013_auto_20201120_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('publication_list.html', 'publication_list.html'), ('publication_view_hero_original.html', 'publication_view_hero_original.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_v1.html', 'portale_home_v1.html'), ('portale_home_dipartimento_v3.html', 'portale_home_dipartimento_v3.html'), ('portale_home_v_original.html', 'portale_home_v_original.html'), ('portale_home_dipartimento_v3_dimes.html', 'portale_home_dipartimento_v3_dimes.html'), ('portale_home_v3.html', 'portale_home_v3.html'), ('publication_list_brython.html', 'publication_list_brython.html'), ('portale_home_v2.html', 'portale_home_v2.html')], max_length=1024),
        ),
    ]
