# Generated by Django 3.1.2 on 2020-11-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_templates', '0016_auto_20201123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='template_file',
            field=models.CharField(choices=[('dipartimento_home_v3_dimes.html', 'dipartimento_home_v3_dimes.html'), ('publication_list.html', 'publication_list.html'), ('publication_view_hero_original.html', 'publication_view_hero_original.html'), ('publication_view.html', 'publication_view.html'), ('portale_home_v_original.html', 'portale_home_v_original.html'), ('portale_home_v3.html', 'portale_home_v3.html'), ('dipartimento_home_v3.html', 'dipartimento_home_v3.html'), ('publication_list_brython.html', 'publication_list_brython.html')], max_length=1024),
        ),
    ]
