# Generated by Django 3.1.2 on 2020-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201011_2114'),
        ('cms_pages', '0002_auto_20201010_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard Page'), ('custom', 'Custom Page'), ('home', 'Home Page')], default='standard', max_length=33),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
